/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ADSCController */

#ifndef _Included_ADSCController
#define _Included_ADSCController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ADSCController
 * Method:    doCCDStartExposure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDStartExposure
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDStopExposure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDStopExposure
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDStatus
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDState
  (JNIEnv *, jobject);


/*
 * Class:     ADSCController
 * Method:    doCCDSetReadFileName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetReadFileName 
(JNIEnv *, jobject, jstring);

/*
 * Class:     ADSCController
 * Method:    doCCDSetFileName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetFileName 
(JNIEnv *, jobject, jstring);

/*
 * Class:     ADSCController
 * Method:    doCCDSetFilePar
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL 
Java_dl_px_detector_ADSCController_doCCDSetHeaderTime
(JNIEnv *env, jobject obj, jdouble time);

/*
 * Class:     ADSCController
 * Method:    doCCDSetHeaderTime
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL 
Java_dl_px_detector_ADSCController_doCCDSetHeaderOscillation
(JNIEnv *env, jobject obj, jdouble oscillation);

/*
 * Class:     ADSCController
 * Method:    doCCDSetHeaderOscillation
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL 
Java_dl_px_detector_ADSCController_doCCDSetHeaderPhi
(JNIEnv *env, jobject obj, jdouble phiAngle);

/*
 * Class:     ADSCController
 * Method:    doCCDSetHeaderPhi
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL 
Java_dl_px_detector_ADSCController_doCCDSetHeaderDistance
(JNIEnv *env, jobject obj, jdouble distance);

/*
 * Class:     ADSCController
 * Method:    doCCDSetHeaderDistance
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL 
Java_dl_px_detector_ADSCController_doCCDSetHeaderWavelength
(JNIEnv *env, jobject obj, jdouble wavelength);

/*
 * Class:     ADSCController
 * Method:    doCCDSetHeaderWavelength
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL 
Java_dl_px_detector_ADSCController_doCCDSetHeaderBeamX
(JNIEnv *env, jobject obj, jdouble x);

/*
 * Class:     ADSCController
 * Method:    doCCDSetHeaderBeamX
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL 
Java_dl_px_detector_ADSCController_doCCDSetHeaderBeamY
(JNIEnv *env, jobject obj, jdouble y);

/*
 * Class:     ADSCController
 * Method:    doCCDSetHeaderBeamY
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetFilePar
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     ADSCController
 * Method:    doCCDGetFilePar
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDGetFilePar
  (JNIEnv *, jobject, jint);

/*
 * Class:     ADSCController
 * Method:    doCCDSetHwPar
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetHwPar
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     ADSCController
 * Method:    doCCDGetHwPar
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDGetHwPar
  (JNIEnv *, jobject, jint);

/*
 * Class:     ADSCController
 * Method:    doCCDSetReadFile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetReadFile
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDClearReadFile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDClearReadFile
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDSetBin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetBin
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDClearBin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDClearBin
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDGetBin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDGetBin
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDSlowAdc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSlowAdc
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDFastAdc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDFastAdc
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDSaveRaw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSaveRaw
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDNoRaw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDNoRaw
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDSetXform
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetXform
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDClearXform
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDClearXform
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDSetDark0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetDark0
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDSetDark1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetDark1
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDClearDark
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDClearDark
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDManualDarkMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDManualDarkMode
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDAutoDarkMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDAutoDarkMode
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDSetLastImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDSetLastImage
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDClearLastImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDClearLastImage
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDGetImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDGetImage
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDCorrectImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDCorrectImage
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDWriteImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDWriteImage
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDGetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDGetLastError
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDAbort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDAbort
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDReset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDReset
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    doCCDInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dl_px_detector_ADSCController_doCCDInitialize
  (JNIEnv *, jobject);

/*
 * Class:     ADSCController
 * Method:    initFIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dl_px_detector_ADSCController_initFIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
