int	get_moddb(struct q_moddef *qm, int max_c, char *fname, int ignore_host);
int	rep_write(int fd, char *buf,int count);
void	notify_server_eof(int   fd, int received_errno);
void	mult_host_dbfd_setup();
int	receive_data_raw(int ind);
int	save_image(int which_kind,int  buffer_kind, int compress);
int	receive_data_cor(int ind);
int	save_image_with_convert_smv(int compress);
int	save_image_with_convert_cbf(int compress);
void	initial_defaults();
int	get_xform_status(char *sbuf);
void	util_3digit(char *s1, int val);
int	getparam_action(int no);
int	setparam_action(int no, char *str);
int	connect_to_host_api(int	*fdnet, char *host, int port, char *msg);
int	connect_to_host(int	*fdnet, char *host, int port, char *msg);
int	probe_port_raw(int fd);
void	cleanexit(int status);
void	timestamp(FILE *fp);
void	process_input();
int	process_buffer();
int	execute_command();
int	timeGetTime();
int	read_port_raw(int fd, char *stbuf, int stbufsize);
int	test_communications(int bn, int *padc, int *pser);
int	reset_controller(int bn);
